name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files (Debugging)
        run: ls -la

      - name: Install Dependencies
        run: |
          cd backend  # Change this if your project structure is different
          npm install

      - name: Build Application
        run: |
          cd backend
          npm run build  # If you have a build step

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          APPLICATION_NAME: "AMS_Application"
          ENVIRONMENT_NAME: "lms-backend-env"
        run: |
          pip install awsebcli --upgrade --user
          export PATH=$HOME/.local/bin:$PATH
          cd backend
          eb init $APPLICATION_NAME --platform node.js --region $AWS_REGION
          eb use $ENVIRONMENT_NAME
          eb deploy
