name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure compatibility

      - name: Change to Frontend Directory & Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Verify Build Output
        run: |
          cd frontend
          ls -la dist/

      - name: Update AWS CLI
        run: |
          sudo /usr/local/aws-cli/v2/current/bin/aws --version
          sudo /usr/local/aws-cli/v2/current/bin/aws install --update
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check AWS CLI Version
        run: aws --version
        
      - name: List AWS CloudFront Commands (Debugging)
        run: aws cloudfront help
        

      - name: Deploy to S3
        run: |
          cd frontend
          aws s3 sync dist/ s3://awscloudbucketbuild --delete

      - name: Invalidate CloudFront Cache
        run: |
            export PATH=$HOME/.local/bin:$PATH
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        
